CREATE TABLE IF NOT EXIST QUESTIONNAIRE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXIST QUESTION (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTIONNAIRE_ID INT NOT NULL,
    QUESTION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);


CREATE TABLE IF NOT EXIST REPONSE (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTION_ID INT NOT NULL,
    QUESTIONAIRE_ID INT NOT NULL
    REP VARCHAR(255) NOT NULL, -- Valeur de la réponse
    TYPE_REPONSE VARCHAR(255) NOT NULL, -- TEXT, RADIO, CHECKBOX
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)
    FOREIGN KEY (QUESTIONAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);

-- requete de selection

SELECT * FROM QUESTIONNAIRE;

SELECT * FROM QUESTION;

SELECT * FROM REPONSE;

-- choisire le questionnaire 1 et afficher les questions

SELECT * FROM QUESTION WHERE QUESTIONNAIRE_ID = 1;

-- selon une question, afficher les reponses
SELECT * FROM REPONSE WHERE QUESTION_ID = 1;





