CREATE TABLE IF NOT EXISTS QUESTIONNAIRE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOM_QUESTIONAIRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS QUESTION (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTIONNAIRE_ID INT NOT NULL,
    QUESTION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);

CREATE TABLE IF NOT EXISTS REPONSE (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTION_ID INT NOT NULL,
    QUESTIONNAIRE_ID INT NOT NULL,
    REP VARCHAR(255) NOT NULL,
    CORRECT BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);


CREATE TABLE IF NOT EXISTS USER (
    ID int NOT NULL AUTO_INCREMENT,
    PSEUDO varchar(100) NOT NULL,
    MAIL varchar(100) NOT NULL,
    MDP text NOT NULL,
    DATE_INSCRIPTION datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TYPEDECOMPTE varchar(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS NOTE_USER(
    ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    QUESTIONNAIRE_ID int NOT NULL,
    NOTE int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
); 
