CREATE TABLE IF NOT EXISTS QUESTIONNAIRE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOM_QUESTIONAIRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS QUESTION (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTIONNAIRE_ID INT NOT NULL,
    QUESTION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);

CREATE TABLE IF NOT EXISTS REPONSE (
    ID INT NOT NULL AUTO_INCREMENT,
    QUESTION_ID INT NOT NULL,
    QUESTIONNAIRE_ID INT NOT NULL,
    REP VARCHAR(255) NOT NULL,
    CORRECT BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID),
    FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID)
);


-- requete de selection

--SELECT * FROM QUESTIONNAIRE;

--SELECT * FROM QUESTION;

--SELECT * FROM REPONSE;

-- choisire le questionnaire 1 et afficher les questions

--SELECT * FROM QUESTION WHERE QUESTIONNAIRE_ID = 1;

-- selon une question, afficher les reponses
--SELECT * FROM REPONSE WHERE QUESTION_ID = 1;





