-- modele d'insertion de questionnaire
-- VALEUR (ID, NAME)
INSERT INTO QUESTIONNAIRE (NAME) VALUES ('Questionnaire 1');
INSERT INTO QUESTIONNAIRE (NAME) VALUES ('Questionnaire 2');
INSERT INTO QUESTIONNAIRE (NAME) VALUES ('Questionnaire 3');

-- modele d'insertion de question
-- VALEUR (ID, QUESTIONNAIRE_ID, QUESTION)
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (1, 'Combien de temps fais une journée ?');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (1, 'Combien de temps fais une semaine ?');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (1, 'Combien de temps fais un mois ?');

-- modele d'insertion de reponse
-- VALEUR (ID, QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE)
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (1, 1, '24h', 'TEXT');
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (1, 1, '7j', 'RADIO');
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (1, 1, '30j', 'TEXT');

INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (2, 'Quelle valeurs font 10km ?');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (2, 'Quelle valeurs font 1m ?');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION) VALUES (2, 'Quelle valeurs font 1ha ?');

INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (4, 2, '10 000m', 'CHECKBOX');
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (4, 2, '100hm', 'CHECKBOX');
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (4, 2, '1m', 'CHECKBOX');
INSERT INTO REPONSE (QUESTION_ID, QUESTIONAIRE_ID, REP, TYPE_REPONSE) VALUES (4, 2, '100ha', 'CHECKBOX');
