--Verifier le ID de question 

INSERT INTO QUESTIONNAIRE (NOM_QUESTIONAIRE) VALUES ('Questionnaire 1');
INSERT INTO QUESTIONNAIRE (NOM_QUESTIONAIRE) VALUES ('Questionnaire 2');
INSERT INTO QUESTIONNAIRE (NOM_QUESTIONAIRE) VALUES ('Questionnaire 3');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (1, 'Combien de temps dure une journée ?', 'radio');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (1, 'Combien de temps dure une semaine ?', 'select' );
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (1, 'Combien font 10+10 ?', 'radio');

INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (1, 1, '24 heures', TRUE );
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (1, 1, '12 heures', FALSE );
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (1, 1, '28 heures', FALSE );


INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (2, 1, '7 jours', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (2, 1, '8 jours', FALSE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (2, 1, '9 jours', FALSE);



INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (3, 1, '20', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (3, 1, '40', FALSE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (3, 1, '30', FALSE);

INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (2, 'Quelle est la valeur de 10 km ?', 'radio');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (2, 'Quelle est la valeur de 10 dm ?', 'select');
INSERT INTO QUESTION (QUESTIONNAIRE_ID, QUESTION,TYPE_QUESTION) VALUES (2, 'Quelle est la valeur de 1 ha ?', 'checkbox');

INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (4, 2, '10 000 m', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (4, 2, '1 000 m', FALSE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (4, 2, '100 000 m', FALSE);

INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (5, 2, '1 m', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (5, 2, '10  m', FALSE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (5, 2, '100 m', FALSE);

INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (6, 2, '10 000 m²', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (6, 2, '10 0000 dm²', TRUE);
INSERT INTO REPONSE (QUESTION_ID, QUESTIONNAIRE_ID, REP, CORRECT) VALUES (6, 2, '100 000 m²', FALSE); 

 